// src/app/layout.js
import "./globals.css";
import QueryLayout from "./QueryLayout";

export const metadata = {
  title: "Server Side Rendering",
  description: "Generated by Web Developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryLayout>{children}</QueryLayout>
      </body>
    </html>
  );
}
